// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MAAS
List MAAS(const arma::mat& A1, const arma::mat& A2, const arma::mat& A3, arma::vec& dims);
RcppExport SEXP _MAAS_MAAS(SEXP A1SEXP, SEXP A2SEXP, SEXP A3SEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A3(A3SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(MAAS(A1, A2, A3, dims));
    return rcpp_result_gen;
END_RCPP
}
// adjustPeak
NumericMatrix adjustPeak(NumericMatrix pp, NumericMatrix cc, DataFrame overlapRegion, double eta);
RcppExport SEXP _MAAS_adjustPeak(SEXP ppSEXP, SEXP ccSEXP, SEXP overlapRegionSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type overlapRegion(overlapRegionSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(adjustPeak(pp, cc, overlapRegion, eta));
    return rcpp_result_gen;
END_RCPP
}
// intersectRegions
DataFrame intersectRegions(CharacterVector peaks, CharacterVector cnvs);
RcppExport SEXP _MAAS_intersectRegions(SEXP peaksSEXP, SEXP cnvsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cnvs(cnvsSEXP);
    rcpp_result_gen = Rcpp::wrap(intersectRegions(peaks, cnvs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MAAS_MAAS", (DL_FUNC) &_MAAS_MAAS, 4},
    {"_MAAS_adjustPeak", (DL_FUNC) &_MAAS_adjustPeak, 4},
    {"_MAAS_intersectRegions", (DL_FUNC) &_MAAS_intersectRegions, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MAAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
