# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MAAS <- function(A1, A2, A3, dims) {
    .Call(`_MAAS_MAAS`, A1, A2, A3, dims)
}

adjustPeak <- function(pp, cc, overlapRegion, eta = 0.2) {
    .Call(`_MAAS_adjustPeak`, pp, cc, overlapRegion, eta)
}

intersectRegions <- function(peaks, cnvs) {
    .Call(`_MAAS_intersectRegions`, peaks, cnvs)
}

